name: AI Automation Generator (English)
version: "3.0.0"
slug: gemini-ai-en
description: Generate Home Assistant automations with Google Gemini AI - English Version
url: https://github.com/ago19800/AI-Automation-Generator-Google-Gemini-
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true
ingress_port: 8099
panel_icon: mdi:robot
panel_title: AI Automation EN
homeassistant_api: true
hassio_api: true
hassio_role: manager
ports:
  8099/tcp: null
options:
  google_api_key: ""
schema:
  google_api_key: str
