name: AI Automation Generator (Google)
version: "2.7.3"
slug: gemini-ai
description: Genera automazioni con AI - Versione senza login + Editor YAML
url: https://github.com/ago19800/AI-Automation-Generator-Google-Gemini-
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true
ingress_port: 8099
panel_icon: mdi:robot
panel_title: AI Automation
homeassistant_api: true
hassio_api: true
hassio_role: manager
ports:
  8099/tcp: null
options:
  google_api_key: ""
schema:
  google_api_key: str
